import { Inter } from 'next/font/google'
import './globals.css'
import Context from '@/context/Context'
import Modal from '@/components/shared/modal/Modal'
import Toast from '@/components/shared/toast/Toast'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Context>
          {children}
          <Modal />
          <Toast />
        </Context>
      </body>
    </html>
  )
}
